# 资源管理与出错处理

## defer调用

- 确保调用在函数结束时发生 

- ```go
  package main
  
  import "fmt"
  
  func tryDefer() {
     defer fmt.Println(1) //在函数return之前打印出来
     defer fmt.Println(2)
     fmt.Println(3)
  }
  func main() {
     tryDefer()
  }
  ```

  defer本质上是一个栈区，也就是后声明的先进行，先声明的后进行

  defer保证语句在函数return之前打印出来

  为什么需要这样的操作，资源管理也就是所谓的例如文件关闭，释放一类的操作，利用defer进行管理，更加方便

我们利用之前编写的斐波那契数列

```go
package fib

func Fibonacci() func() int {
   a, b := 0, 1
   return func() int {
      a, b = b, a+b
      return a
   }
}
```

我们将结果写入到一个文件当中，代码如下

```go
func writeFile(filename string) {
   file, err := os.Create(filename)
   if err != nil {
      panic(err)
   }
   defer file.Close() //关闭文件
   writer := bufio.NewWriter(file) //利用一个缓冲区进行写入操 作
    defer writer.Flush() //将缓冲区的内容统一写入
   f := fib.Fibonacci()
   for i := 0; i < 20; i++ {
      fmt.Fprintln(writer, f())
   }
}
func main() {
   writeFile("fib.txt")
}
```

这样我们实现了异常处理以及文件的写入，对于defer我们有如下的

![image-20220714165710782](Images/image-20220714165710782.png)

这样我们就实现了操作，然后我们需要知道这里参数在defer语句时进行计算，我们编写以下函数

```go
func tryDefer() {
   for i := 0; i < 100; i++ {
      defer fmt.Println(i)
      if i == 30 {
         panic("printed too many")
      }
   }
}
```

这里我们会发现结果为

```go
30
29
28
27
26
25
24
23
22
21
20
19
18
17
16
15
14
13
12
11
10
9 
8 
7 
6 
5
4
3
2
1
0
panic: printed too many

goroutine 1 [running]:
main.tryDefer()
        D:/goproject/awesomeProject1/errhandling/defer.go:14 +0xc7
main.main()
        D:/goproject/awesomeProject1/errhandling/defer.go:32 +0x17

Process finished with the exit code 2

```

